### ISSUE TITLE
[SUGGESTION] Bring back the F1-3 keybinds

### ISSUE THREAD

**Issue by richardios275** [Tria-Studio/TRIA-Issues#98] opened 2022-09-24 11:30 UTC
**Is your feature request related to a problem? Please describe.**
This feature was a thing in 0.8, but it seems to be removed unintentionally in 0.9. So this is a reminder to bring it back.

**Describe the solution you'd like**
Just like before, F1 to open the map menu, F2 to open spectate, and F3 to open settings. I'm not sure if the gamepad D-Pad keybinds are gone like the keyboard shortcuts since my gamepad is broken.

**Additional context**
Nothing

**Comment by azzzertyy** [comment] 2022-09-29 00:52
planned
idk why theyre gone

**Comment by azzzertyy** [comment] 2022-09-29 00:54
although duplicate of #91

**Closed** 2022-09-29 00:54 UTC
Labels: duplicate, suggestion, planned

**Comment by KryptonForce102** [comment] 2022-09-29 02:44
> planned
> idk why theyre gone

My pr fixed this not sure if it’s merged yet
