### ISSUE TITLE
[SUGGESTION] Change the mobile swimming buttons

### ISSUE THREAD

**Issue by shaimoons** [Tria-Studio/TRIA-Issues#40] opened 2022-07-05 01:17 UTC
**Is your feature request related to a problem? Please describe.**
My friend who plays on mobile noticed the buttons for 'swim up' and 'swim down' were changed to be their own buttons, and were made smaller. They are hard to press due to their small sizes and new positions. It is also harder to memorize because 'swim up' used to be assigned to 'jump', and 'swim down' to 'shift lock', which is how it is on computer. The new buttons are also not labeled, and 'swim down' does not work if a map has sliding enabled, since the 'slide' button and the 'swim down' button will overlap.

**Describe the solution you'd like**
Requesting a change where 'swim up' is the jump button, and where 'swim down' is the shift lock button. Also, increase the size of the shift lock button to the size of the jump button when the player is swimming, so it is easier to press 'swim down'. This is the way it worked before 0.8, the shift lock button would increase in diameter so swimming down is easier. The shift lock button would revert to its normal size when the player exits the water.

**Additional context**
Pictures for comparison:

The buttons: 
![mobile1](https://user-images.githubusercontent.com/108696728/177219050-c93d8425-d9f9-4cfc-9276-9ad8bb4f1ce9.png)

What the buttons should be changed to: 
![mobile2](https://user-images.githubusercontent.com/108696728/177219060-5ed256e8-bcfa-4222-9276-ea0598804196.png)

**Comment by Ethan76167** [comment] 2022-07-26 03:23
duplicate of #37

**Closed** 2022-07-26 03:27 UTC
Labels: suggestion
